liip-amboss/forge

docs/frontend/tooling/README.md
frontend/README.md
frontend/package.json
frontend/src/components/HelloWorld.vue
frontend/src/main.js
frontend/src/plugins/vueAxe.js
frontend/yarn.lock

Accessiblity tools

---

frontend/.eslintrc.js
frontend/babel.config.js
frontend/jest.config.js
frontend/package-lock.json
frontend/postcss.config.js
frontend/prettier.config.js
frontend/src/components/HelloWorld.vue
frontend/src/main.js
frontend/src/plugins/vueAxe.js
frontend/src/store.js
frontend/src/styleguide/Section.vue
frontend/src/views/Home.vue
frontend/src/views/Styleguide.vue
frontend/tailwind.config.js
frontend/tests/e2e/specs/test.js
frontend/tests/unit/.eslintrc.js
frontend/tests/unit/example.spec.js

Just ran npm lint after merging your request

Fix linting

---

docs/frontend/components/toggle.md
docs/frontend/css/README.md
frontend/package-lock.json
frontend/package.json
frontend/src/App.vue
frontend/src/assets/css/base/elements.postcss
frontend/src/styleguide/CodeExample.vue
frontend/src/styleguide/Section.vue
frontend/src/styleguide/SectionSub.vue
frontend/src/styleguide/Typography.vue
frontend/src/views/Home.vue
frontend/src/views/Styleguide.vue
frontend/tailwind.config.js

Introduce tailwind-typography

---

.github/pr_frontend.md

This file is mostly only relevant to frontend

Create a Pull request template

---

docs/frontend/testing.md
frontend/babel.config.js
frontend/package-lock.json
frontend/package.json

Tell me if you wanted more, or something specific.

Document testing a bit

---

.github/pr_frontend.md

Deleted the old PR template because we have a newer one

Deleted old PR template

---

.gitignore
docs/.vuepress/config.js
docs/frontend/ConnectingApis.md
frontend/package-lock.json
frontend/package.json
frontend/src/components/HelloWorld.vue
frontend/src/examples/APIUsage.vue
frontend/src/models/mtg-card.model.js
frontend/src/services/api.js
frontend/src/services/mtg-card.service.js

Introduce first example of handling data nicely

---

backend/requirements/base.txt
backend/requirements/dev.txt
backend/requirements/test.txt

Update all backend packages to be upToDate with the newest Django version

feat: update django to latest version

---

frontend/package-lock.json

Recreated the package-lock.json which fixes some version problems

Recreate package-lock.json

---

README.MD

Changed the contribution linked to our code of conduct.

fix: change link to wrong repo

---

backend/app/settings.py
backend/app/urls.py
backend/requirements/base.in
backend/requirements/base.txt
backend/requirements/dev.in
backend/requirements/dev.txt
backend/requirements/test.txt

#82 Summary of this PR
Add django restframework per default to the repo.

feat: add django restframwork to repo

---

frontend/src/App.vue
frontend/src/components/Login.vue
frontend/src/locales/de.json
frontend/src/views/Welcome.vue
frontend/vue.config.js

Clean up frontend and add further translations

feat: add furter translations and fix url

---

docker-compose.yml

Pass the INITIAL env var to the docker container

---

frontend/src/components/Modal.vue

Modal fix 👺

---

docs/.vuepress/config.js
frontend/package-lock.json

Fix code formatting

---

backend/app/settings.py

#82 Summary of this PR
Fix the configuration of the static and media files folders

fix: change path config

---

frontend/src/services/api.js
frontend/src/store/Auth.js

#82 Summary of this PR
Fix the refresh token workflow, as it was not implemented correctly

fix: change refresh token worflow

---

.env.dist
frontend/src/main.js

Add possibility to disable vueaxe

---

backend/app/urls.py

#82 Summary of this PR
Redirect the backend instead of adding a default route, so we have a default url for the backend

feat: redirect non existing links to backend

---

kubernetes/backend/backend-deployment.yaml
kubernetes/backend/backend-service.yaml
kubernetes/backend/kustomization.yaml
kubernetes/base/kustomization.yaml
kubernetes/db/db-deployment.yaml
kubernetes/db/db-service.yaml
kubernetes/db/kustomization.yaml
kubernetes/frontend/frontend-deployment.yaml
kubernetes/frontend/frontend-service.yaml
kubernetes/frontend/kustomization.yaml
kubernetes/k8s_deploy.bash
kubernetes/migration-job/kustomization.yaml
kubernetes/migration-job/migration-job.yaml

Add kubernetes yamls

---

backend/accounts/urls.py
backend/accounts/views.py
backend/app/settings.py
backend/app/urls.py
backend/requirements/base.in
backend/requirements/base.txt
backend/requirements/dev.txt
backend/requirements/test.txt

feat: add redoc api documentation

---

docs/.vuepress/config.js
docs/frontend/components/Multiselect.md
frontend/src/components/Select.vue
frontend/src/examples/BasicDropdown.vue
frontend/src/examples/MultiSelectDropdown.vue

I wanted to add t he Multiselect from the last project to forge... only to notice, that it already exists in the almost same fashion. I still added the simplified version and tried to improve the documentation a bit.

Improve the select

---

.gitlab-ci.yml
backend/.flake8
backend/accounts/admin.py
backend/accounts/migrations/0001_initial.py
backend/accounts/migrations/0003_user_phone_number.py
backend/accounts/migrations/0004_alter_user_first_name.py
backend/accounts/models.py
backend/accounts/serializers.py
backend/accounts/urls.py
backend/accounts/views.py
backend/app/settings.py
backend/app/urls.py
backend/requirements/test.in
backend/requirements/test.txt

feat: add pipelines for testing in gitlab

---

frontend/src/components/Login.vue
frontend/src/router/index.js
frontend/src/router/routes.js
frontend/src/views/Dashboard.vue
frontend/src/views/Login.vue

fix: rename components to fix redirects
